# Generated by Django 3.0.5 on 2020-04-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsOfExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SphereOfBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1)),
                ('age', models.IntegerField()),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('sphere_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.SphereOfBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='SubtypeOfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=100)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_management_app.ItemsOfExpenditure')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('subtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_management_app.SubtypeOfItem')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('sphere_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.SphereOfBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='ChequePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('cheque_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.Cheque')),
                ('keyword_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.Keywords')),
            ],
        ),
        migrations.AddField(
            model_name='cheque',
            name='institution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.InstitutionKeywords'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='user_consumer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.UserConsumer'),
        ),
    ]
