# Generated by Django 3.0.5 on 2020-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequepositions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userconsumer',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
