# Generated by Django 3.0.5 on 2020-05-16 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_finance_management_app', '0002_auto_20200501_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userconsumer',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userconsumer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userconsumer',
            name='password',
        ),
        migrations.AddField(
            model_name='userconsumer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconsumer',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж')], max_length=7),
        ),
    ]
