# Generated by Django 3.0.5 on 2020-05-24 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_finance_management_app', '0003_auto_20200516_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='user_consumer_id',
        ),
        migrations.AddField(
            model_name='cheque',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
