# Generated by Django 3.0.5 on 2020-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_management_app', '0004_auto_20200524_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
