# Generated by Django 3.0.5 on 2020-05-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_management_app', '0005_auto_20200531_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequepositions',
            name='keyword_id',
        ),
        migrations.AddField(
            model_name='chequepositions',
            name='subtype_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_finance_management_app.SubtypeOfItem'),
        ),
    ]
