# Generated by Django 3.0.5 on 2020-04-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_experience', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_foodstuff', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('dishes', models.ManyToManyField(to='restaurant.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='orders',
            field=models.ManyToManyField(to='restaurant.Order'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('cost_of_delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_on_time', models.BooleanField()),
                ('foodstuffs', models.ManyToManyField(to='restaurant.Foodstuff')),
            ],
        ),
    ]
